# --- File Konfigurasi Final ---

# Section untuk server, disarankan dari forum agar aset termuat dengan benar
[server]
headless = true

# Section untuk browser
[browser]
gatherUsageStats = false

# Section untuk tema kustom Anda
[theme]
# Tentukan tema dasar agar tidak kembali ke hitam
base = "light"

# Warna-warna yang Anda inginkan
primaryColor = "#1c64d1"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#e3eefd"
textColor = "#0a101d"

# Pengaturan font yang kita coba aktifkan kembali
font = "Plus Jakarta Sans"
