# File Konfigurasi Tema Streamlit

[theme]

# Warna utama untuk widget interaktif (tombol, slider, dll.)
# Saya pilih biru yang serasi dengan sidebar.
primaryColor = "#1c64d1"

# Warna latar belakang utama aplikasi
backgroundColor = "#FFFFFF" # Putih

# Warna latar belakang untuk sidebar
secondaryBackgroundColor = "#e3eefd" # Biru muda yang sangat lembut

# Warna teks utama pada background putih
textColor = "#0a101d"

# Jenis Font (Streamlit akan otomatis mengambil dari Google Fonts)
font = "Roboto"
